"""
MCPManager — owns the lifecycle of the local weather MCP server and gives
the rest of the backend a simple way to:
  1. see what tools are available (`list_tool_schemas`, in each LLM
     provider's own wire format), and
  2. actually run one (`execute_tool`).

This is Task 2 from the Technical Task Definition. It deliberately knows
nothing about FastAPI or any specific LLM provider — main.py wires those
together. That separation is what makes it easy to point this at a
different MCP server later (just change `server_script`) without touching
any LLM or HTTP code.
"""

from __future__ import annotations

import logging
from contextlib import AsyncExitStack
from pathlib import Path
from typing import Any, Literal

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from mcp.types import Tool as MCPTool

logger = logging.getLogger("mcp_client")

# Providers we know how to translate an MCP tool schema into. Add a new
# entry here (and a matching branch in `_to_<provider>_schema`) if you wire
# up another LLM API.
Provider = Literal["anthropic", "gemini"]


def _strip_unsupported_schema_keys(schema: dict[str, Any]) -> dict[str, Any]:
    """Recursively drop JSON-Schema keys that Gemini's function-calling
    schema doesn't understand (it only supports a subset of OpenAPI 3.0).

    MCP tool schemas are generated by Pydantic and often include `title`
    and `additionalProperties`, which Gemini rejects with a 400 if left in.
    Anthropic's Claude API is more permissive and doesn't need this.
    """
    if not isinstance(schema, dict):
        return schema

    dropped_keys = {"title", "additionalProperties", "$schema"}
    cleaned = {k: v for k, v in schema.items() if k not in dropped_keys}

    if "properties" in cleaned and isinstance(cleaned["properties"], dict):
        cleaned["properties"] = {
            name: _strip_unsupported_schema_keys(prop) for name, prop in cleaned["properties"].items()
        }

    return cleaned


class MCPManager:
    """Manages one MCP server subprocess (the local `weather.py` script)
    over stdio, plus the ClientSession talking to it.

    Usage (see main.py's lifespan for the real thing):
        manager = MCPManager()
        await manager.connect()
        ... use manager.list_tool_schemas() / manager.execute_tool() ...
        await manager.close()
    """

    def __init__(self, server_script: str | Path = "weather.py", python_executable: str = "python3"):
        self.server_script = str(Path(server_script).resolve())
        self.python_executable = python_executable

        self.session: ClientSession | None = None
        self.tools: list[MCPTool] = []

        # AsyncExitStack lets us open the stdio transport + ClientSession
        # (both of which are async context managers) and keep them alive
        # for the whole life of the FastAPI app, then close both cleanly
        # with a single `await self._exit_stack.aclose()` on shutdown.
        self._exit_stack = AsyncExitStack()

    async def connect(self) -> None:
        """Spawn the weather MCP server as a subprocess and initialize a
        session with it. Populates `self.tools` with whatever tools the
        server advertises (see weather.py's `@mcp.tool()` functions).
        """
        server_params = StdioServerParameters(
            command=self.python_executable,
            args=[self.server_script],
        )

        logger.info("Starting MCP server subprocess: %s %s", self.python_executable, self.server_script)

        read_stream, write_stream = await self._exit_stack.enter_async_context(stdio_client(server_params))
        session = await self._exit_stack.enter_async_context(ClientSession(read_stream, write_stream))

        await session.initialize()
        list_tools_result = await session.list_tools()

        self.session = session
        self.tools = list_tools_result.tools

        logger.info("Connected to MCP server. Available tools: %s", [t.name for t in self.tools])

    async def close(self) -> None:
        """Cleanly tear down the ClientSession and terminate the MCP server
        subprocess. Safe to call even if `connect()` was never called.
        """
        await self._exit_stack.aclose()
        self.session = None
        self.tools = []
        logger.info("MCP server subprocess terminated.")

    def list_tool_schemas(self, provider: Provider) -> list[dict[str, Any]]:
        """Return the currently-known MCP tools, translated into whatever
        shape `provider`'s chat-completions API expects for its `tools`
        parameter.
        """
        if provider == "anthropic":
            return [self._to_anthropic_schema(tool) for tool in self.tools]
        if provider == "gemini":
            return [self._to_gemini_schema(tool) for tool in self.tools]
        raise ValueError(f"Unknown provider: {provider!r}")

    @staticmethod
    def _to_anthropic_schema(tool: MCPTool) -> dict[str, Any]:
        # Anthropic's Messages API tool schema:
        # https://docs.claude.com/en/docs/build-with-claude/tool-use
        return {
            "name": tool.name,
            "description": tool.description or "",
            "input_schema": tool.inputSchema,
        }

    @staticmethod
    def _to_gemini_schema(tool: MCPTool) -> dict[str, Any]:
        # Gemini's function-calling schema wraps a `FunctionDeclaration` in
        # a `parameters` field, and only accepts a subset of JSON Schema.
        return {
            "name": tool.name,
            "description": tool.description or "",
            "parameters": _strip_unsupported_schema_keys(tool.inputSchema),
        }

    async def execute_tool(self, name: str, arguments: dict[str, Any]) -> str:
        """Run one MCP tool by name and return its result as plain text,
        ready to be handed straight back to the LLM as a tool result.
        """
        if self.session is None:
            raise RuntimeError("MCPManager.execute_tool() called before connect()")

        logger.info("Executing tool %s(%s)", name, arguments)
        result = await self.session.call_tool(name, arguments)

        # A tool result is a list of "content blocks" (usually just one
        # text block for our weather tools). Join them in case a tool
        # ever returns more than one.
        text_parts = [block.text for block in result.content if hasattr(block, "text")]
        return "\n".join(text_parts) if text_parts else "(tool returned no content)"
